sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fibonacci_test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true fibonacci_test npm test

after_success:
  - docker build -t fibonacci-client ./client
  - docker build -t fibonacci-nginx ./nginx
  - docker build -t fibonacci-server ./server
  - docker build -t fibonacci-worker ./worker
  # Log in to the docker cli/hub
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  # Take these images and push to docker hub
  - docker tag fibonacci-client kunalv/fibonacci-client
  - docker tag fibonacci-server kunalv/fibonacci-server
  - docker tag fibonacci-nginx kunalv/fibonacci-nginx
  - docker tag fibonacci-worker kunalv/fibonacci-worker
  - docker push kunalv/fibonacci-client
  - docker push kunalv/fibonacci-server
  - docker push kunalv/fibonacci-nginx
  - docker push kunalv/fibonacci-worker

